package com.aegorov.knowledgeplatform.ragservice.application.llm;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import com.aegorov.knowledgeplatform.ragservice.application.retrieval.RetrievedChunk;

import reactor.core.publisher.Flux;

/**
 * Offline, deterministic {@link ChatLlm} used when
 * {@code knowledge-platform.llm.provider=stub} (the default).
 * <p>
 * It does not call any model. Instead it composes a readable answer that
 * paraphrases the retrieved chunks and cites the source documents it "used",
 * then emits that answer as several fixed-size fragments so the UI visibly
 * streams. Output is a pure function of the {@link LlmContext}, so tests are
 * stable. When no chunks were retrieved it clearly says so.
 */
public class StubChatLlm implements ChatLlm {

    private static final int FRAGMENT_SIZE = 48;
    private static final int MAX_CITED_CHUNKS = 3;
    private static final int SNIPPET_CHARS = 180;

    @Override
    public Flux<String> stream(LlmContext context) {
        String answer = compose(context);
        return Flux.fromIterable(fragment(answer));
    }

    private String compose(LlmContext context) {
        String question = context.question() == null ? "" : context.question().strip();
        List<RetrievedChunk> chunks = context.chunks();

        if (chunks == null || chunks.isEmpty()) {
            return "I could not find any relevant indexed sources for your question"
                    + (question.isEmpty() ? "" : " \"" + question + "\"")
                    + ". Try uploading a related document first, then ask again. "
                    + "(This is the offline stub model; configure Azure OpenAI to get real answers.)";
        }

        StringBuilder builder = new StringBuilder();
        builder.append("Based on the indexed documents, here is what I found");
        if (!question.isEmpty()) {
            builder.append(" for \"").append(question).append('"');
        }
        builder.append(":\n\n");

        int cited = Math.min(MAX_CITED_CHUNKS, chunks.size());
        for (int i = 0; i < cited; i++) {
            RetrievedChunk chunk = chunks.get(i);
            builder.append(i + 1)
                    .append(". From document ")
                    .append(chunk.documentId());
            if (chunk.fileName() != null && !chunk.fileName().isBlank()) {
                builder.append(" (").append(chunk.fileName()).append(')');
            }
            builder.append(" (chunk #")
                    .append(chunk.chunkIndex())
                    .append(", similarity ")
                    .append(String.format("%.2f", chunk.score()))
                    .append("): ")
                    .append(snippet(chunk.content()))
                    .append('\n');
        }

        builder.append("\nSources:\n")
                .append(chunks.stream()
                        .limit(cited)
                        .map(this::sourceLine)
                        .collect(Collectors.joining("\n")))
                .append('\n');
        builder.append("\n\n(This answer was generated by the offline stub model; "
                + "swap in Azure OpenAI to synthesise a natural-language response.)");
        return builder.toString();
    }

    private String sourceLine(RetrievedChunk chunk) {
        StringBuilder line = new StringBuilder("- ");
        if (chunk.fileName() != null && !chunk.fileName().isBlank()) {
            line.append(chunk.fileName());
        } else {
            line.append(chunk.documentId());
        }
        if (chunk.link() != null && !chunk.link().isBlank()) {
            line.append(" (").append(chunk.link()).append(')');
        }
        line.append(" [").append(chunk.documentId()).append('#').append(chunk.chunkIndex()).append(']');
        return line.toString();
    }

    private String snippet(String content) {
        if (content == null) {
            return "";
        }
        String normalized = content.strip().replaceAll("\\s+", " ");
        if (normalized.length() <= SNIPPET_CHARS) {
            return normalized;
        }
        return normalized.substring(0, SNIPPET_CHARS) + "...";
    }

    private List<String> fragment(String text) {
        List<String> fragments = new ArrayList<>();
        for (int start = 0; start < text.length(); start += FRAGMENT_SIZE) {
            fragments.add(text.substring(start, Math.min(text.length(), start + FRAGMENT_SIZE)));
        }
        if (fragments.isEmpty()) {
            fragments.add(text);
        }
        return fragments;
    }
}
